### ISSUE TITLE
Cloning repo reports "Invalid Password"

### ISSUE THREAD

**Issue by ekumahost** [claytonsavage/Social-Network#1]
```
 git clone https://github.com/blockmason/social-network-demo
Cloning into 'social-network-demo'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/blockmason/social-network-demo/'

```
how is one suppose to authenticate!?

**Comment by canterberry** [comment]
Hi @ekumahost,

The error you encountered was because the repo was not hosted at the location documented in the README.

The repo has now been moved to https://github.com/blockmason/social-network-demo, as documented. Please try again.

Thanks for reporting the discrepancy!
